pip install plyer
pip install cfscrape
pip install colorama
pip install tasksio
pip install getpass
pip install asyncio
pip install websocket
pip install requests
pip install selenium
pip install discord_webhook
pip install plyer
pip install discord
pip install discord.py
pip install beautifulsoup4
pip install Pillow
pip install PyAutoGui
pip install pyperclip
pip install aiohttp
pip install pypresence
pip install dhooks
pip install pyinstaller
pip install datetime
pip install PIL
pip install gtts
pip install ctypes